@startuml
class core.beta.Beta {
Class dedicated to the generation and manipulation of a beta grid
  - kind
  - to_index
  - generate_grid()
  - from_dE()
  - from_parameters()
  - get_Eout()
  - scale()
}

class core.alpha.Alpha {
Class dedicated to the generation and manipulation of a alpha grid
 - to_index
 - generate_grid()
 - from_parameters()
 - get_theta()
 - scale()
}
class core.s.Sab {
Class dedicated to the generation and manipulation of S(alpha, -beta) matrix
- alpha
- beta
- to_sym()
- from_fgm()
- from_sct()
- from_pdos()
- get_beta()
- get_alpha()
- get_value_from_Alpha_beta()
- get_matrix_from_parameters()
- get_scattering_func()
}
Alpha *-- Sab : contains
Beta *-- Sab : contains

class core.material.pdos.Pdos{
phonon density of states of a material
- rho
- from_data()
- to_beta_grid(T)
- plot()
- P(T)
- Teff(T)
- DebyeWallerCoeff(T)
- get_tau(T, nphonon, beta)
}
class core.material.material_composition.Atom{
Objective: Save in one object all the basic properties of the atom:
+ A
+ Z
+ atom_mass
+ b: {"b_coh": b_coh, "b_incoh": b_incoh}
- name
- zam
- boundXs
- boundIncXs
-freeXs
}
core.material.material_composition.Atom *-- core.material.material_composition.Molecule : contains
class core.material.material_composition.Molecule{
Objective: Save in one class all the atomic properties of the different atoms
of the molecule.
- name
}
class core.material.crystal_symmetry.Crystal_structure{
Objective: Save the all related to crystal structure in a class
+ length
+ angles
- operator
- dir_vector
- unit_cell_volume
- reciproc_vec
}
class core.material.solid.Solid{
Combination of molecule in a specific position in space
- unit_pos
- atom_pos
- atom_number
}
core.material.material_composition.Molecule *-- core.material.solid.Solid : contains
core.material.crystal_symmetry.Crystal_structure *-- core.material.solid.Solid : contains

class core.target_material.Target_mat{
Real target material
- get_Bfact()
- get_multiplicity()
- get_BraggEdges()
- get_coherent_Xs()
- get_Sab()
- get_Inelastic_XS()
}
core.material.solid.Solid *-- core.target_material.Target_mat : contains
core.material.pdos.Pdos *-- core.target_material.Target_mat : contains
core.s.Sab *-- core.target_material.Target_mat : contains
class UserInputChoice{
+ T
+ Ein
+ theta
}
UserInputChoice -> core.target_material.Target_mat
@enduml